### ISSUE TITLE
Tracking issue for unimplemented HTTP headers

### ISSUE THREAD

**Issue by Lord-McSweeney** [Lord-McSweeney/c-http#1]
Unimplemented request headers:

- [ ] [`Accept`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept)
- [ ] [`Authorization`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization)
- [ ] [`Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie)
- [ ] [`Referer`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer)

Unimplemented response headers (these are currently ignored):
- [ ] [`Set-Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)
- [ ] Refresh
- [ ] [`WWW-Authenticate`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate)
